<?php

use Application\Controller\DesignController;
use Application\Controller\HelperController;

?>
<div class="main-wrapper">
    <div class="small-banner-container with-breadcrumb">
        <div class="small-banner_img">
            <img src="<?php echo HelperController::getImageUrl($this->banner->imageName); ?>" />
        </div>
        <div class="small-banner-caption-container centered">
            <div class="container">
                <?php if ($this->banner->caption1) { ?>
                    <div class="banner-title1"><?php echo $this->banner->caption1; ?></div>
                <?php } ?>
                <!-- <div class="banner-title2">Get Ready!</div> -->
                <?php if ($this->banner->caption2) { ?>
                <div class="banner-title3"><?php echo $this->banner->caption2; ?></div>
                <?php } ?>
            </div>
        </div>
        <div class="banner-breadcrumb">
            <div class="container">
                <ul>
                    <li><a href="<?php echo MAIN_URL; ?>"><span><img src="img/home-icon.jpg" /></span>Home</a></li>
                    <li><a class="light">BEST DEALS</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="breadcrumb-c d-block d-sm-none">
        <div class="breadcrumb-c-inner">
            <div class="container">
                <ul>
                    <li><a href="<?php echo MAIN_URL; ?>"><span><img src="img/home-icon.jpg" /></span>Home</a></li>
                    <li><a class="">BEST DEALS</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 with-margin">
                <?php echo DesignController::mainTitle("BEST DEALS") ?>
            </div>
        </div>
        <div class="row">
            <?php ?>
            <?php foreach ($this->items as $item) { ?>
                <div class="col-6 col-md-3 item-col">
                    <?php echo DesignController::item($item); ?>
                </div>
            <?php } ?>

        </div>

        <div class="row">
            <div class="col-md-12">
                <div id="product-pagination" class="product-pagination text-center"></div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function() {
        //alert('s');
        //Pagination
        $("#product-pagination").twbsPagination({
            totalPages: <?php echo $this->totalPages; ?>,
            visiblePages: 5,
            first: "",
            last: "",
            next: '<i class="fas fa-chevron-right"></i>',
            prev: '<i class="fas fa-chevron-left"></i>',
            startPage: <?php echo $this->currentPage; ?>,
            initiateStartPageClick: false,
            onPageClick: function(event, page) {
                location.href = '<?php echo MAIN_URL . 'best-deals' . "/?page="; ?>' + page;
            },
        });
    });
</script>