<?php

use Application\Controller\HelperController;

if ($this->banners) { ?>
  <div class="main-banner-container">
    <div class="main-banner-overlay">
      <?php if ($this->isHome) { ?>
        <div class="banner-menu d-none d-sm-block">
          <div class="container">
            <div class="row">
              <div class="col-md-6 text-right right-column">
                <div class="categories">
                  <div class="start-here">start here</div>
                  <ul>
                    <li><a class="categories-title" href="#">OUR CATEGORIES</a></li>
                    <li id="line1"><a href="<?php echo MAIN_URL . 'products?' . http_build_query(['c' => ['1']])?>">SCHOOL FURNITURE</a></li>
                    <li id="line2"><a href="<?php echo MAIN_URL . 'products?' . http_build_query(['c' => ['17']])?>">OUTDOOR SUPPLIES</a></li>
                    <li><a href="<?php echo MAIN_URL . 'products?' . http_build_query(['c' => ['19']])?>">LEARNING TOYS</a></li>
                    <li><a href="<?php echo MAIN_URL . 'products?' . http_build_query(['c' => ['18']])?>">SMALL SUPPLIES</a></li>
                    <li><a id="line3" href="<?php echo MAIN_URL . 'products?' . http_build_query(['c' => ['20']])?>">SPECIALITY ITEMS</a></li>
                  </ul>
                </div>
              </div>
              <div class="col-md-6 text-left left-column">
                <div class="categories-labels">
                  <div>
                    <div id="line1-1" class="label purple">ARE YOU A<br><span>SCHOOL?</span></div>
                  </div>
                  <div>
                    <div id="line2-2" class="label blue">ARE YOU A<br><span>PARENT?</span></div>
                  </div>
                  <div>
                    <div id="line3-3" class="label green">TAKE A LOOK<br><span>AROUND</span></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <?php } ?>
    </div>
    <div class="" id="main-banner">
      <?php foreach ($this->banners as $row) { ?>
        <div>
          <div class="banner-item">
            <div class="banner-item_img"><img src="<?php echo HelperController::getImageUrl($row->imageName); ?>" title=""></div>
            <?php if ($row->caption1) { ?>
              <div class="banner-item_caption1"><?php echo $row->caption1; ?></div>
            <?php } ?>
            <?php if ($row->caption2) { ?>
              <div class="banner-item_caption2"><?php echo $row->caption2; ?></div>
            <?php } ?>
            <?php if ($row->buttonText && $row->buttonLink) { ?>
              <div class="banner-item_button"><a href="<?php echo $row->buttonLink; ?>"><?php echo $row->buttonText; ?></a></div>
            <?php } ?>
          </div>
        </div>
      <?php } ?>
    </div>
  </div>
<?php }
?>