<?php
$contentMySqlExtDAO = new ContentMySqlExtDAO();
$facebook = $contentMySqlExtDAO->queryBySlug('facebook')[0];
$instagram = $contentMySqlExtDAO->queryBySlug('instagram')[0];
?>
<div class="qualities-wrap <?php if (empty($this->isHome)) {
                                echo 'dark';
                            } ?>">
    <div class="container">
        <div class="row">
            <div class="col text-center">
                <img src="img/quality1.png" />
                <div class="quality-item">Pre Sales Services</div>
            </div>
            <div class="col text-center">
                <img src="img/quality2.png" />
                <div class="quality-item">On-Time Delivery</div>
            </div>
            <div class="col text-center">
                <img src="img/quality3.png" />
                <div class="quality-item">Quality</div>
            </div>
            <div class="col text-center">
                <img src="img/quality4.png" />
                <div class="quality-item">Warranty</div>
            </div>
            <div class="col text-center">
                <img src="img/quality5.png" />
                <div class="quality-item">Aftersales Support</div>
            </div>
        </div>
    </div>
</div>
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12 footer1">
                <div class="row">
                    <div class="col">
                        <div class="logo-social">
                            <div class="footer-logo">
                                <img src="img/logo.png?v=1.0.0" />
                            </div>
                            <div class="social-media">
                                <a href="<?php echo $facebook->customUrl; ?>" target="_blank"><i class="fab fa-facebook-f"></i></a>
                                <a href="<?php echo $instagram->customUrl; ?>" target="_blank"><i class="fab fa-instagram"></i></a>
                                <a href="<?php echo $instagram->customUrl; ?>" target="_blank"><i class="fab fa-snapchat-ghost"></i></a>
                                <a href="<?php echo $instagram->customUrl; ?>" target="_blank"><i class="fab fa-linkedin-in"></i></a>
                                <a href="<?php echo $instagram->customUrl; ?>" target="_blank"><i class="fab fa-whatsapp"></i></a>
                                <!-- <a href="https://twitter.com" target="_blank"><img src="img/twitter.png" /></a> -->
                            </div>
                        </div>
                    </div>
                    <div class="col footer-menu">
                        <div class="footer-menu_title">SCHOOLERSMART</div>
                        <ul>
                            <li><a href="<?php echo MAIN_URL . 'page/about-us' ?>">About us</a></li>
                            <li><a href="<?php echo MAIN_URL . 'careers' ?>">Careers</a></li>
                            <li><a href="<?php echo MAIN_URL . 'contact-us' ?>">Contact us</a></li>
                            <li><a href="<?php echo MAIN_URL . 'page/terms-conditions' ?>">Terms & conditions</a></li>
                            <li><a href="<?php echo MAIN_URL . 'page/frequently-asked-questions' ?>">FAQ's</a></li>
                        </ul>
                    </div>
                    <div class="col footer-menu">
                        <div class="footer-menu_title">USEFUL LINKS</div>
                        <ul>
                            <!-- <li><a href="javascript:void(0);">News/Events</a></li> -->
                            <li><a href="<?php echo MAIN_URL . 'promotions' ?>">Promotions</a></li>
                            <li><a href="<?php echo MAIN_URL . 'latest-arrivals' ?>">Latest Arrivals</a></li>
                            <li><a href="<?php echo MAIN_URL . 'page/delivery-and-shipping'; ?>">Delivery And Shipping</a></li>
                        </ul>
                    </div>
                    <div class="col footer-menu">
                        <div class="footer-menu_title">INFORMATION CENTER</div>
                        <ul>
                            <li><a href="javascript:void(0);" data-toggle="modal" data-target="#login-signup-modal">Sign In</a></li>
                            <li><a href="<?php echo MAIN_URL . 'my-cart'; ?>">My Cart</a></li>
                            <li><a href="<?php echo MAIN_URL . 'my-wishlist'; ?>">My Wishlist</a></li>
                            <li><a href="<?php echo MAIN_URL . 'page/return-policy'; ?>">Return Policy</a></li>
                            <li><a href="<?php echo MAIN_URL . 'page/warranty'; ?>">Warranty</a></li>
                        </ul>
                    </div>
                    <div class="col footer-menu">
                        <div class="footer-menu_title">KNOW US BETTER</div>
                        <ul>
                            <li><a href="<?php echo MAIN_URL . 'my-cart'; ?>">My Cart</a></li>
                            <li><a href="<?php echo MAIN_URL . 'my-wishlist'; ?>">My Wishlist</a></li>
                            <li><a href="<?php echo MAIN_URL . 'page/return-policy'; ?>">Return Policy</a></li>
                            <li><a href="<?php echo MAIN_URL . 'page/warranty'; ?>">Warranty</a></li>
                            <?php if (IS_MULTI_VENDOR) { ?>
                                <li><a href="<?php echo MAIN_URL . 'vendor-login'; ?>">Vendor Area</a></li>
                            <?php } ?>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 footer2">
                <p><?php echo SITE_TITLE . ' &copy; ' . date('Y') ?> All rights reserved, powered by <a href="http://thirteencube.com" target="_blank">Thirteencube</a></p>
            </div>
        </div>
    </div>
    <div class="floating-wpp"></div>
</footer>
<pre>
    <?php print_r($_SESSION); ?>
</pre>