<?php

use Application\Controller\CategoryController;
use Application\Controller\DesignController;
use Application\Controller\HelperController;
use Application\Controller\ProductController;
use Application\Controller\UserController;
use Application\Controller\OptionsController;

$searchWord = isset($_GET['search']) && $_GET['search'] ? $_GET['search'] : "";
$cartCount = 0;
$cartItems = [];
if (isset($_SESSION['user'])) {
    $cartCount = count($_SESSION['user']->cart);
    $itemMySqlExtDAO = new ItemMySqlExtDAO();
    $cartItems = $itemMySqlExtDAO->getCartItemsByUserId($_SESSION['user']->id);
    //print_r($cartItems);
}

$wishlistCount = 0;
if (isset($_SESSION['user'])) {
    $wishlistCount = count($_SESSION['user']->wishlist);
}

global $categories;
$level1Categories = CategoryController::getCategories('parent_id = 0 ORDER BY display_order ASC, name ASC, id DESC');
$categories = $level1Categories;
//print_r($categories);echo '<br>';
$c = 0;
foreach ($level1Categories as $row) {
    $categories[$c]->subcategories = CategoryController::getCategories("parent_id = $row->id and active = 1 ORDER BY mega_menu_display_order ASC, name ASC, id DESC");
    $c1 = 0;
    foreach ($categories[$c]->subcategories as $row1) {
        $categories[$c]->subcategories[$c1]->subsubcategories = CategoryController::getCategories("parent_id = $row1->id and active = 1 ORDER BY display_order ASC, name ASC, id DESC");
        $c1++;
    }
    $c++;
}
?>
<header class="main-header">
    <div class="container-fluid">
        <div class="middle-menu clearfix">
            <div class="logo-container">
                <a href="<?php echo MAIN_URL ?>"><img src="img/logo.png?v=1.0.0" /></a>
            </div>
            <div class="buttons-container">
                <span class="dropdown-wrap">
                    <div class="dropdown">
                        <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Select Currency
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </div>
                </span>
                <span>
                    <a href="<?php echo MAIN_URL . 'my-wishlist';?>"><img src="img/heart<?php echo !empty($this->header2) ? '-dark' : '';?>.png" /></a>
                    <span class="badge"><?php echo $wishlistCount; ?></span>
                </span>
                <span class="cart-wrapper">
                    <a href="javascript:void(0);">
                        <img src="img/bag<?php echo !empty($this->header2) ? '-dark' : '';?>.png" />
                    </a>
                    <span class="badge"><?php echo $cartCount; ?></span>
                    <div class="compact-cart-wrapper">
                        <?php echo DesignController::compactCartItems($cartItems);?>
                    </div>
                </span>
                <span>
                    <a href="javascript:void(0);"><img src="img/search-icon<?php echo !empty($this->header2) ? '-dark' : '';?>.png" /></a>
                </span>
                <span class="custom-menu-closed">
                    <a class="open-custom-menu" href="javascript:void(0);"><img src="img/menu-toggle<?php echo !empty($this->header2) ? '-dark' : '';?>.png" /></a>
                    <a class="close-custom-menu" href="javascript:void(0);"><img src="img/menu-toggle-closed.png" /></a>
                </span>
                <div class="custom-menu">
                    <div class="custom-menu-nav">
                        <ul>
                            <li><a href="#">HOME</a></li>
                            <li><a href="#">ABOUT US</a></li>
                            <li><a href="#">IDEAS & RESOURCES</a></li>
                            <li><a href="#">CONTACT US</a></li>
                        </ul>
                    </div>
                    <div class="shop-btn"><a href="#">SHOP</a></div>
                    <div class="social-media">
                        <a href="<?php echo $facebook->customUrl; ?>" target="_blank"><i class="fab fa-facebook-f"></i></a>
                        <a href="<?php echo $instagram->customUrl; ?>" target="_blank"><i class="fab fa-instagram"></i></a>
                        <a href="<?php echo $instagram->customUrl; ?>" target="_blank"><i class="fab fa-snapchat-ghost"></i></a>
                        <a href="<?php echo $instagram->customUrl; ?>" target="_blank"><i class="fab fa-linkedin-in"></i></a>
                        <a href="<?php echo $instagram->customUrl; ?>" target="_blank"><i class="fab fa-whatsapp"></i></a>
                        <!-- <a href="https://twitter.com" target="_blank"><img src="img/twitter.png" /></a> -->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php //echo $this->partial('layout/menu/desktop-menu') 
    ?>
    <?php //echo $this->partial('layout/menu/mobile-menu') 
    ?>
</header>