<?php

use Application\Controller\CategoryController;
use Application\Controller\DesignController;
use Application\Controller\HelperController;

global $cartCount;
global $cartItems;
$searchWord = isset($_GET['search']) && $_GET['search'] ? $_GET['search'] : "";
$cartCount = 0;
$cartItems = [];
if (isset($_SESSION['user'])) {
    $cartCount = count($_SESSION['user']->cart);
    $itemMySqlExtDAO = new ItemMySqlExtDAO();
    $cartItems = $itemMySqlExtDAO->getCartItemsByUserId($_SESSION['user']->id);
    //print_r($cartItems);
}

$wishlistCount = 0;
if (isset($_SESSION['user'])) {
    $wishlistCount = count($_SESSION['user']->wishlist);
}

global $categories;
$level1Categories = CategoryController::getCategories('parent_id = 0 ORDER BY display_order ASC, name ASC, id DESC');
$categories = $level1Categories;
//print_r($categories);echo '<br>';
$c = 0;
foreach ($level1Categories as $row) {
    $categories[$c]->subcategories = CategoryController::getCategories("parent_id = $row->id and active = 1 ORDER BY mega_menu_display_order ASC, name ASC, id DESC");
    $c1 = 0;
    foreach ($categories[$c]->subcategories as $row1) {
        $categories[$c]->subcategories[$c1]->subsubcategories = CategoryController::getCategories("parent_id = $row1->id and active = 1 ORDER BY display_order ASC, name ASC, id DESC");
        $c1++;
    }
    $c++;
}

// Get Currencies
global $currencies;
global $selectedCurrency;
$currencyMySqlExtDAO = new CurrencyMySqlExtDAO();
$currencies = $currencyMySqlExtDAO->queryAllOrderBy('display_order ASC');
$selectedCurrency = isset($_SESSION['currency']) ? $_SESSION['currency'] : 'USD';
if (!isset($_SESSION['rate']) || !isset($_SESSION['currency'])) {
    $selectedCurrencyInfo = $currencyMySqlExtDAO->queryByCurrencyName($selectedCurrency);
    $_SESSION['rate'] = $selectedCurrencyInfo[0]->conversionRate;
    $_SESSION['currency'] = $selectedCurrency;
    header('Location: ' . HelperController::getCurrentUrl());
    exit();
}
?>
<header class="main-header">
    <div class="container-fluid">
        <div>

        </div>
    </div>
    <div class="middle-menu d-none d-sm-block">
        <nav class="navbar navbar-light navbar-expand-md justify-content-center">
            <a href="<?php echo MAIN_URL ?>"><img src="img/logo.png?v=1.0.0" /></a>
            <button class="navbar-toggler ml-1" type="button" data-toggle="collapse" data-target="#collapsingNavbar2">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse justify-content-between align-items-center w-100" id="collapsingNavbar2">
                <ul class="navbar-nav mx-auto text-center main-menu">

                    <li class="nav-item active"><a class="nav-link" href="<?php echo MAIN_URL; ?>">HOME</a></li>
                    <li class="nav-item"><a class="nav-link" href="<?php echo MAIN_URL . 'page/about-us' ?>">ABOUT US</a></li>
                    <li class="nav-item"><a class="nav-link" href="<?php echo MAIN_URL . 'ideas-resources'; ?>">IDEAS & RESOURCES</a></li>
                    <li class="nav-item"><a class="nav-link" href="<?php echo MAIN_URL . 'contact-us' ?>">CONTACT US</a></li>
                    <?php /*<li class="nav-item"><a class="nav-link" href="<?php echo MAIN_URL . 'products' ?>">SHOP</a></li>*/ ?>
                    <li class="nav-item dropdown mega-dropdown shopdropdown">
                        <a href="<?php echo MAIN_URL . 'shop'; ?>" class="dropdown-toggle nav-link" data-tossggles="dropdown">SHOP <span class="glyphicon glyphicon-chevron-down pull-right"></span></a>

                        <div class="dropdown-menu mega-dropdown-menu mega-menu-wrap">
                            <div class="container">
                                <div class="row">
                                    <div class="col-3">
                                        <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                                            <?php
                                            $c = 0;

                                            foreach ($level1Categories as $row) {
                                                $additionalClass = "";
                                                if ($c == 0) {
                                                    $additionalClass = " active";
                                                } ?>
                                                <a class="nav-link <?php echo $additionalClass; ?>" href="<?php echo MAIN_URL . 'shop/' . $row->slug; ?>" role="tab"><?php echo $row->name; ?></a>
                                            <?php $c++;
                                            } ?>
                                        </div>
                                    </div>
                                    <div class="col-9">
                                        <div class="tab-content p-3" id="v-pills-tabContent">
                                            <?php
                                            $c = 0;

                                            foreach ($level1Categories as $row) {
                                                $additionalClass = "";
                                                if ($c == 0) {
                                                    $additionalClass = " show active";
                                                } ?>
                                                <div class="tab-pane fade <?php echo $additionalClass; ?>" id="v-pills-<?php echo $row->id ?>" role="tabpanel" aria-labelledby="v-pills-profile-tab">
                                                    <h5><?php echo $row->name; ?></h5>
                                                    <?php $subCatgeories = CategoryController::getCategories("parent_id = $row->id and active = 1 ORDER BY mega_menu_display_order ASC, name ASC, id DESC"); ?>
                                                    <ul>
                                                        <?php foreach ($subCatgeories as $sub) { ?>
                                                            <li><a href="<?php echo MAIN_URL . 'shop/' . $row->slug . '/' . $sub->slug; ?>"><?php echo $sub->name; ?></a></li>
                                                        <?php } ?>
                                                    </ul>
                                                </div>
                                            <?php $c++;
                                            } ?>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </li>

                </ul>
            </div>
            <div class="navbar-collapse collapse justify-content-stretch" id="navbar7">
                <ul class="navbar-nav ml-auto">

                    <li class="nav-item">
                        <span class="dropdown-wrap">
                            <div class="dropdown">
                                <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Currency: <?php echo $selectedCurrency; ?>
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <?php foreach ($currencies as $currency) { ?>
                                        <a class="dropdown-item currency-item" href="javascript:void(0);" data-currency="<?php echo $currency->currencyName; ?>" data-rate="<?php echo $currency->conversionRate; ?>"><?php echo $currency->currencyName; ?></a>
                                    <?php } ?>
                                </div>
                            </div>
                        </span>
                    </li>
                    <li class="nav-item">
                        <?php if (isset($_SESSION['user'])) { ?>
                            <span class="dropdown-wrap">
                                <div class="dropdown">
                                    <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Welcome <?php echo $_SESSION['user']->firstName; ?>
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item" href="<?php echo MAIN_URL . 'my-orders'; ?>">My Orders</a>
                                        <a class="dropdown-item" href="<?php echo MAIN_URL . 'my-wishlist'; ?>">My Wishlist</a>
                                        <a class="dropdown-item" href="<?php echo MAIN_URL . 'logout'; ?>">Logout</a>
                                    </div>
                                </div>
                            </span>
                        <?php } else { ?>
                            <span class="login-logout-wrap"><a href="javascript:void(0);" data-toggle="modal" data-target="#login-signup-modal"><i data-feather="user"></i></a></span>
                        <?php } ?>
                    </li>
                    <li class="nav-item">
                        <span>
                            <a href="<?php echo MAIN_URL . 'my-wishlist'; ?>"><i data-feather="heart"></i></a>
                            <span class="badge"><?php echo $wishlistCount; ?></span>
                        </span>
                    </li>
                    <li class="nav-item">
                        <span class="cart-wrapper">
                            <a href="javascript:void(0);">
                                <i data-feather="shopping-cart"></i>
                            </a>
                            <span class="badge"><?php echo $cartCount; ?></span>
                            <div class="compact-cart-wrapper">
                                <?php echo DesignController::compactCartItems($cartItems); ?>
                            </div>
                        </span>
                    </li>
                    <li class="nav-item">
                        <span class="search-wrapper">
                            <a href="javascript:void(0);"><i data-feather="search"></i></a>
                            <div class="search-wrapper-inner">
                                <form method="GET" action="<?php echo MAIN_URL . 'products' ?>">
                                    <div class="input-group">
                                        <input type="text" class="form-control" placeholder="Search ..." name="search">
                                        <div class="input-group-append">
                                            <button class="btn" type="submit">
                                                <i data-feather="search"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </span>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
    <div class="container-fluid">

        <div class="middle-menu d-none d-sm-block clearfix" style="display: none !important;">
            <div class="logo-container">
                <a href="<?php echo MAIN_URL ?>"><img src="img/logo.png?v=1.0.0" /></a>
            </div>
            <div class="buttons-container">
                <?php if (isset($_SESSION['user'])) { ?>
                    <span class="dropdown-wrap">
                        <div class="dropdown">
                            <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Welcome <?php echo $_SESSION['user']->firstName; ?>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" href="<?php echo MAIN_URL . 'my-orders'; ?>">My Orders</a>
                                <a class="dropdown-item" href="<?php echo MAIN_URL . 'my-wishlist'; ?>">My Wishlist</a>
                                <a class="dropdown-item" href="<?php echo MAIN_URL . 'logout'; ?>">Logout</a>
                            </div>
                        </div>
                    </span>
                <?php } else { ?>
                    <span class="login-logout-wrap"><a href="javascript:void(0);" data-toggle="modal" data-target="#login-signup-modal">Login / Register</a></span>
                <?php } ?>
                <span class="dropdown-wrap">
                    <div class="dropdown">
                        <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Select Currency: <?php echo $selectedCurrency; ?>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <?php foreach ($currencies as $currency) { ?>
                                <a class="dropdown-item currency-item" href="javascript:void(0);" data-currency="<?php echo $currency->currencyName; ?>" data-rate="<?php echo $currency->conversionRate; ?>"><?php echo $currency->currencyName; ?></a>
                            <?php } ?>
                        </div>
                    </div>
                </span>
                <span>
                    <a href="<?php echo MAIN_URL . 'my-wishlist'; ?>"><img src="img/heart<?php echo !empty($this->header2) ? '-dark' : ''; ?>.png" /></a>
                    <span class="badge"><?php echo $wishlistCount; ?></span>
                </span>
                <span class="cart-wrapper">
                    <a href="javascript:void(0);">
                        <img src="img/bag<?php echo !empty($this->header2) ? '-dark' : ''; ?>.png" />
                    </a>
                    <span class="badge"><?php echo $cartCount; ?></span>
                    <div class="compact-cart-wrapper">
                        <?php echo DesignController::compactCartItems($cartItems); ?>
                    </div>
                </span>
                <span class="search-wrapper">
                    <a href="javascript:void(0);"><img src="img/search-icon<?php echo !empty($this->header2) ? '-dark' : ''; ?>.png" /></a>
                    <div class="search-wrapper-inner">
                        <form method="GET" action="<?php echo MAIN_URL . 'products' ?>">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Search ..." name="search">
                                <div class="input-group-append">
                                    <button class="btn" type="submit">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </span>
                <span class="custom-menu-closed">
                    <a class="open-custom-menu" href="javascript:void(0);"><img src="img/menu-toggle<?php echo !empty($this->header2) ? '-dark' : ''; ?>.png" /></a>
                    <a class="close-custom-menu" href="javascript:void(0);"><img src="img/menu-toggle-closed.png" /></a>
                </span>
                <div class="custom-menu">
                    <div class="custom-menu-nav">
                        <ul>
                            <li><a href="<?php echo MAIN_URL; ?>">HOME</a></li>
                            <li><a href="<?php echo MAIN_URL . 'page/about-us' ?>">ABOUT US</a></li>
                            <li><a href="<?php echo MAIN_URL . 'ideas-resources'; ?>">IDEAS & RESOURCES</a></li>
                            <li><a href="<?php echo MAIN_URL . 'contact-us' ?>">CONTACT US</a></li>
                        </ul>
                    </div>
                    <div class="shop-btn"><a href="<?php echo MAIN_URL . 'products' ?>">SHOP</a></div>
                    <div class="social-media">
                        <a href="<?php echo $facebook->customUrl; ?>" target="_blank"><i class="fab fa-facebook-f"></i></a>
                        <a href="<?php echo $instagram->customUrl; ?>" target="_blank"><i class="fab fa-instagram"></i></a>
                        <a href="<?php echo $instagram->customUrl; ?>" target="_blank"><i class="fab fa-snapchat-ghost"></i></a>
                        <a href="<?php echo $instagram->customUrl; ?>" target="_blank"><i class="fab fa-linkedin-in"></i></a>
                        <a href="<?php echo $instagram->customUrl; ?>" target="_blank"><i class="fab fa-whatsapp"></i></a>
                        <!-- <a href="https://twitter.com" target="_blank"><img src="img/twitter.png" /></a> -->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php //echo $this->partial('layout/menu/desktop-menu') 
    ?>
    <?php echo $this->partial('layout/menu/mobile-menu')
    ?>
</header>