<?php
global $categories;
global $currencies;
global $cartCount;
global $cartItems;
global $selectedCurrency;

use Application\Controller\DesignController;
?>
<div class="upper-menu d-block d-sm-none">
    <div class="container">
        <div class="buttons-container">
            <?php if (isset($_SESSION['user'])) { ?>
                <span class="dropdown-wrap">
                    <div class="dropdown">
                        <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Hi <?php echo $_SESSION['user']->firstName; ?>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="<?php echo MAIN_URL . 'my-orders'; ?>">My Orders</a>
                            <a class="dropdown-item" href="<?php echo MAIN_URL . 'my-wishlist'; ?>">My Wishlist</a>
                            <a class="dropdown-item" href="<?php echo MAIN_URL . 'logout'; ?>">Logout</a>
                        </div>
                    </div>
                </span>
            <?php } else { ?>
                <span class="login-logout-wrap"><a href="javascript:void(0);" data-toggle="modal" data-target="#login-signup-modal">Login / Register</a></span>
            <?php } ?>
            <span class="dropdown-wrap">
                <div class="dropdown">
                    <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <?php echo $selectedCurrency; ?>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <?php foreach ($currencies as $currency) { ?>
                            <a class="dropdown-item currency-item" href="javascript:void(0);" data-currency="<?php echo $currency->currencyName; ?>" data-rate="<?php echo $currency->conversionRate; ?>"><?php echo $currency->currencyName; ?></a>
                        <?php } ?>
                    </div>
                </div>
            </span>
            <span class="wishlist-wrapper">
                <a href="<?php echo MAIN_URL . 'my-wishlist'; ?>"><img src="img/heart.png" /></a>
                <span class="badge"><?php echo $wishlistCount; ?></span>
            </span>
            <span class="cart-wrapper">
                <a href="javascript:void(0);">
                    <img src="img/bag.png" />
                </a>
                <span class="badge"><?php echo $cartCount; ?></span>
                <div class="compact-cart-wrapper">
                    <?php echo DesignController::compactCartItems($cartItems); ?>
                </div>
            </span>
        </div>
    </div>
</div>
<div class="mobile-menu d-block d-sm-none">
    <nav class="navbar navbar-expand-md navbar-dark navbar-custom">
        <!-- Brand -->
        <a class="navbar-brand" href="#"><img src="img/logo.png" /></a>

        <!-- Toggler/collapsibe Button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Navbar links -->
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="<?php echo MAIN_URL; ?>">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?php echo MAIN_URL . 'shop' ?>">SHOP</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?php echo MAIN_URL . 'page/about-us' ?>">ABOUT US</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">IDEAS & RESOURCES</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?php echo MAIN_URL . 'contact-us' ?>">CONTACT US</a>
                </li>
            </ul>
        </div>
    </nav>
</div>