<?php

use Application\Controller\HelperController;
use Application\Controller\DesignController;

//print_r($this->page);
?>
<div class="main-wrapper">
    <div class="page-banner-wrap about">
        <?php if ($this->page->image) { ?>
            <div class="page-banner">
                <img src="<?php echo HelperController::getImageUrl($this->page->image); ?>" alt="<?php echo $this->page->title; ?>" />
            </div>
        <?php } ?>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <div class="skewed2"><span><?php echo $this->page->title; ?></span></div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-5">
                <div class="row">
                    <?php $c = 1;
                    foreach ($this->images as $row) { ?>
                        <div class="col-md-6">
                            <div class="about-image <?php echo 'img' . $c; ?>">
                                <img src="<?php echo HelperController::getImageUrl($row->imageName); ?>" />
                            </div>
                        </div>
                    <?php $c++;
                    } ?>
                </div>
            </div>
            <div class="col-md-7">
                <div class="page-details">
                    <?php echo $this->page->details; ?>
                </div>
            </div>
        </div>
    </div>
    <div class="diagonal-box blue">
        <div class="content what-makes-wrap">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <div class="column1">
                            <div class="title"><?php echo $this->what->title; ?></div>
                            <div class="subtitle"><?php echo $this->what->subtitle; ?></div>
                            <div class="description"><?php echo $this->what->details; ?></div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="column2">
                            <div class="what-makes-slider">
                                <?php foreach ($this->whatAlbum as $row) { ?>
                                    <div>
                                        <a href="javascript:void(0);">
                                            <img src="<?php echo HelperController::getImageUrl($row->imageName); ?>" />
                                        </a>
                                        <div class="slider-title"><?php echo $row->caption; ?></div>
                                    </div>
                                <?php } ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="our-team-wrap" style="display:none;">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="title-style-2">
                        <div class="title2">MEET</div>
                        <div class="subtitle2">OUR TEAM</div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="team-member-wrap">
                        <div class="team-member-img"><img src="img/team.png" /></div>
                        <div class="team-member-position">BUSINESS DEVELOPMENT</div>
                        <div class="team-member-name">FULL NAME</div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="team-member-wrap">
                        <div class="team-member-img"><img src="img/team.png" /></div>
                        <div class="team-member-position">BUSINESS DEVELOPMENT</div>
                        <div class="team-member-name">FULL NAME</div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="team-member-wrap">
                        <div class="team-member-img"><img src="img/team.png" /></div>
                        <div class="team-member-position">BUSINESS DEVELOPMENT</div>
                        <div class="team-member-name">FULL NAME</div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="team-member-wrap">
                        <div class="team-member-img"><img src="img/team.png" /></div>
                        <div class="team-member-position">BUSINESS DEVELOPMENT</div>
                        <div class="team-member-name">FULL NAME</div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="team-member-wrap">
                        <div class="team-member-img"><img src="img/team.png" /></div>
                        <div class="team-member-position">BUSINESS DEVELOPMENT</div>
                        <div class="team-member-name">FULL NAME</div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="team-member-wrap">
                        <div class="team-member-img"><img src="img/team.png" /></div>
                        <div class="team-member-position">BUSINESS DEVELOPMENT</div>
                        <div class="team-member-name">FULL NAME</div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="team-member-wrap">
                        <div class="team-member-img"><img src="img/team.png" /></div>
                        <div class="team-member-position">BUSINESS DEVELOPMENT</div>
                        <div class="team-member-name">FULL NAME</div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="team-member-wrap">
                        <div class="team-member-img"><img src="img/team.png" /></div>
                        <div class="team-member-position">BUSINESS DEVELOPMENT</div>
                        <div class="team-member-name">FULL NAME</div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="team-member-wrap">
                        <div class="team-member-img"><img src="img/team.png" /></div>
                        <div class="team-member-position">BUSINESS DEVELOPMENT</div>
                        <div class="team-member-name">FULL NAME</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>