<?php

use Application\Controller\HelperController;
use Application\Controller\DesignController;
?>
<div class="main-wrapper">
    <div class="page-banner-wrap">
        <?php if ($this->page->image) { ?>
            <div class="page-banner">
                <img src="<?php echo HelperController::getImageUrl($this->page->image); ?>" alt="<?php echo $this->page->title; ?>" />
            </div>
        <?php } ?>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 page-title">
                <?php echo $this->page->title; ?>
            </div>
            <div class="col-md-12">
                <div class="page-details">
                    <?php echo $this->page->details; ?>
                </div>
            </div>
        </div>
    </div>
</div>