<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

use Application\Controller\DesignController;
use Application\Controller\HelperController;

?>
<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">
            <div class="skewed"><span>WHAT DO YOU WANT TO DO <span>TODAY?</span></span></div>
        </div>

        <?php if (false) { ?>
            <div class="col-md-12">
                <?php echo DesignController::mainTitle('SHOP BY CATEGORIES') ?>
            </div>
            <div class="col-md-12">
                <div class="categories-slider-wrapper">
                    <div id="categories-slider">
                        <?php foreach ($this->featuredCategories as $cat) {
                            $itemCategoryMySqlExtDAO =  new ItemCategoryMySqlExtDAO();
                            if ($cat->parentId == 0) {
                                $url = MAIN_URL . 'products/' . $cat->slug;
                            } else {
                                $parentCategory = $itemCategoryMySqlExtDAO->load($cat->parentId);
                                if ($parentCategory->parentId == 0) {
                                    $url = MAIN_URL . 'products/' . $parentCategory->slug . '/' . $cat->slug;
                                } else {
                                    $mainCategory = $itemCategoryMySqlExtDAO->load($parentCategory->parentId);
                                    $url = MAIN_URL . 'products/' . $mainCategory->slug . '/' . $parentCategory->slug . '/' . $cat->slug;
                                }
                            } ?>
                            <div>
                                <div class="cat-img hover08"><a href="<?php echo $url; ?>"><img src="<?php echo HelperController::getImageUrl($cat->image); ?>" /></a></div>
                                <div class="cat-title"><a href="<?php echo $url; ?>"><?php echo $cat->name; ?></a></div>
                            </div>
                        <?php
                        } ?>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
    <div class="row services-row">
        <?php foreach ($this->services as $service) { ?>
            <div class="col-md-3 col-6 text-center">
                <div class="service-wrap">
                    <div class="service-image"><img src="<?php echo HelperController::getImageUrl($service->image); ?>" /></div>
                    <div class="service-title"><?php echo $service->title; ?></div>
                    <div class="service-slogan"><?php echo $service->subtitle; ?></div>
                </div>

            </div>
        <?php } ?>
    </div>
</div>
<div class="full-width grey hot-selling-ads-wrapper">
    <div class="container">
        <!-- <div class="row hot-selling-ad">
            <div class="col-md-6">
                <div class="title">CHECKOUT OUR</div>
                <div class="subtitle">HOT SELLNG PRODUCTS</div>
                <div class="description">
                    Our main products include desks and chairs for students, iron frame beds,
                    writing chairs, desks, bookshelves and other products.<br><br>
                    They meet the various scenarios used in schools, such as classrooms,
                    dormitories, auditoriums, teachers’ offices, dining halls and other usage scenarios.
                </div>
            </div>
            <div class="col-md-6">
                <div class="hot-selling-slider">
                    <div>
                        <a href="javascript:void(0);">
                            <img src="img/hotselling.png" />
                        </a>
                    </div>
                    <div>
                        <a href="javascript:void(0);">
                            <img src="img/hotselling.png" />
                        </a>
                    </div>
                    <div>
                        <a href="javascript:void(0);">
                            <img src="img/hotselling.png" />
                        </a>
                    </div>
                </div>
            </div>
        </div> -->
        <div class="row hot-selling-ad">
            <div class="col-md-6">
                <div class="title"><?php echo $this->what->title; ?></div>
                <div class="subtitle"><?php echo $this->what->subtitle; ?></div>
                <div class="description"><?php echo $this->what->details; ?></div>
            </div>
            <div class="col-md-6">
                <div class="hot-selling-slider">
                    <?php foreach ($this->whatAlbum as $row) { ?>
                        <div>
                            <a href="javascript:void(0);">
                                <img src="<?php echo HelperController::getImageUrl($row->imageName); ?>" />
                            </a>
                            <div class="slider-title"><?php echo $row->caption; ?></div>
                        </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="start-shopping-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <?php echo DesignController::mainTitle("START SHOPPING <span>today</span>"); ?>
            </div>
            <div class="col-md-12">
                <div class="start-shopping">
                    <?php if ($this->shoppingSlider) {
                        foreach ($this->shoppingSlider as $row) { ?>
                            <div>
                                <div class="slide-wrap">
                                    <div class="slide-wrap-img">
                                        <a href="<?php echo $row->customUrl; ?>"><img src="<?php echo HelperController::getImageUrl($row->image); ?>" /></a>
                                        <div class="slide-label">
                                            <a href="<?php echo $row->customUrl; ?>"><?php echo $row->title; ?></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                    <?php }
                    } ?>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="home-products">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <?php
                echo DesignController::mainTitle("#SCHOOLERSMART", 'with-subtitle');
                echo DesignController::subtitle("OUR LATEST COLLECTION AND PRODUCTS");
                ?>
            </div>
        </div>
        <?php $chunks = array_chunk($this->featuredItems, 8); ?>
        <div class="row">
            <div class="col-md-12">
                <div class="home-products-slider">
                    <?php foreach ($chunks as $chunk) { ?>
                        <div class="home-products-slider-item">
                            <div class="row">
                                <?php foreach ($chunk as $row) {
                                    echo '<div class="col-md-3 col-6">';
                                    echo DesignController::item($row);
                                    echo '</div>';
                                } ?>
                            </div>
                        </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?php if (SHOW_TAGS_SLIDER) { ?>
    <div class="full-width base-color with-slider">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="special-tags">
                        <ul>
                            <li class="active" id="daily-deals"><a href="#">TODAYS DEALS</a></li>
                            <li id="picked-for-you"><a href="#">PICKED FOR YOU</a></li>
                            <li id="best-offers"><a href="#">BEST OFFERS</a></li>
                        </ul>
                    </div>
                    <div class="special-tags-slider-container">
                        <div class="special-tags-slider" id="special-tags-slider-daily-deals">
                            <?php foreach ($this->todaysDeals as $row) {
                                echo '<div>';
                                echo DesignController::item($row);
                                echo '</div>';
                            } ?>
                        </div>
                        <div class="special-tags-slider" id="special-tags-slider-best-offers">
                            <?php foreach ($this->bestOffers as $row) {
                                echo '<div>';
                                echo DesignController::item($row);
                                echo '</div>';
                            } ?>
                        </div>
                        <div class="special-tags-slider" id="special-tags-slider-picked-for-you">
                            <?php foreach ($this->pickedForYou as $row) {
                                echo '<div>';
                                echo DesignController::item($row);
                                echo '</div>';
                            } ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php } ?>

<?php
if (SHOW_HOME_ADS && $this->ads) {
    echo $this->partial('layout/ads');
}
?>